---
- name: Upgrade zabbix
  hosts: TEST
  become: yes

  vars:
    zabbix_version: 5.2

  tasks:

  - name: Check configuration fo zabbix-server
    shell: "which nginx | wc -l"
    register: nginx_status

  - shell: "which mysql | wc -l"
    register: mysql_status

  - name: STOP ZABBIX PROCESSES
    service:
      name: zabbix-server
      state: stopped


  - block: ###BACK UP CONFIGURATION FILES, PHP FILES AND ZABBIX BINARIES###
    - name: create backup dir
      file:
        path: /opt/zabbix-backup/
        state: directory
        mode: 0755

    - name: copy config files when Nginx is installed
      copy: src={{ item }} dest=/opt/zabbix-backup/ remote_src=true
      loop:
        - /etc/zabbix/zabbix_server.conf
        - /etc/nginx/conf.d/zabbix.conf
      when: nginx_status.stdout == "1"

    - name: copy config files when Apache2 is installed
      copy: src={{ item }} dest=/opt/zabbix-backup/ remote_src=true
      loop:
        - /etc/zabbix/zabbix_server.conf
        - /etc/apache2/conf-enabled/zabbix.conf
      when: nginx_status.stdout == "0"

    - name: Copy PHP files
      copy: src=/usr/share/zabbix/ dest=/opt/zabbix-backup/zabbix remote_src=true directory_mode=true

    - name: Copy  Zabbix binaries dir
      shell: "cp -R /usr/share/doc/zabbix-* /opt/zabbix-backup/"


  - block: ###UPDATE REPOSITORY CONFIGURATION PACKAGE###
    - name: removed old repository
      shell: /bin/rm -Rf /etc/apt/sources.list.d/zabbix.list

    - set_fact:
        zabbix_server_apt_repository:
          - "http://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution.lower() }}/"
          - "{{ ansible_distribution_release }}"
          - "main"

    - name: "Installing repository {{ ansible_distribution }}"
      apt_repository:
        repo: "{{ item }} {{ zabbix_server_apt_repository | join(' ') }}"
        state: present
      with_items:
        - deb-src
        - deb

    - name: run update
      apt:
        update_cache: yes


  - block: ###UPGRADE ZABBIX COMPONENTS###
    - name: Upgrade mysql,zabbix,agent
      apt:
        name:
        - zabbix-server-mysql
        - zabbix-frontend-php
        - zabbix-agent
        state: latest
        only_upgrade: yes
      when: mysql_status.stdout == "1"

    - name: Upgrade pgsql,zabbix,agent
      apt:
        name:
        - zabbix-server-pgsql
        - zabbix-frontend-php
        - zabbix-agent
        state: latest
        only_upgrade: yes
      when: mysql_status.stdout == "0"

    - name: install zabbix-apache-conf
      apt:
        name: zabbix-apache-conf
        state: latest
      when: nginx_status.stdout == "0"

    - name: start zabbix-server and agent
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - zabbix-server
        - zabbix-agent
