---
- name: Upgrade mysql,zabbix,agent
  apt:
    name:
    - zabbix-server-mysql
    - zabbix-frontend-php
    - zabbix-agent
    state: latest
    only_upgrade: yes
  when: mysql_status.stdout == "1"

- name: Upgrade pgsql,zabbix,agent
  apt:
    name:
    - zabbix-server-pgsql
    - zabbix-frontend-php
    - zabbix-agent
    state: latest
    only_upgrade: yes
  when: mysql_status.stdout == "0"

- name: install zabbix-apache-conf
  apt:
    name: zabbix-apache-conf
    state: latest
  when: nginx_status.stdout == "0"

- name: upgrade php-fpm for if use nginx
  apt:
    name: php-fpm
    state: latest
    only_upgrade: yes
  when: nginx_status.stdout == "1"

- name: start zabbix-server and agent
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - zabbix-server
    - zabbix-agent
